Add webserver
Auterion/slow-mode-app pull request #2
Opened 2023-10-30 09:08 UTC by marcinolokk

This adds webserver to the application to handle request on `/api/status` endpoint.
A reply follows a pattern where it contains 3 fields:
* `status`: `-1` - ERROR, `0` - LOADING, `1` - SUCCESS, `2` - UNDEFINED
* `status_description`: String describing current state (optional)
* `error`: String describing error (optional)

2023-10-30 16:23 UTC, eyeam3 requested changes

2023-10-30 16:23 UTC, eyeam3 commented on services/slowmode-app/VelocityLimits.cpp
> +    if (_horizontal_speed != horizontal_speed) {
Consider a fuzzy compare for two float values.

2023-10-30 16:23 UTC, eyeam3 commented on services/slowmode-app/VelocityLimits.cpp
> +    if (_vertical_speed != vertical_speed) {
Sane here.

2023-10-30 16:23 UTC, eyeam3 commented on services/slowmode-app/VelocityLimits.cpp
> +    if (_yaw_rate != yaw_rate) {
Same here.

2023-10-30 16:23 UTC, eyeam3 commented on services/slowmode-app/app.cpp
> +        // case app_status_code_t::ERROR:
I don't think this comment is needed.

2023-10-30 16:23 UTC, eyeam3 commented on services/slowmode-app/main.cpp
> +        description = fmt::format("Current limits: ");
Could be just a string.

2023-10-30 16:23 UTC, eyeam3 commented on services/slowmode-app/main.cpp
> +    return;
Remove, or just return the string description.

2023-10-30 16:23 UTC, eyeam3 commented on services/slowmode-app/main.cpp
>          return 0;
This will exit the app and stop the server. It then probably restarts.

2023-11-02 11:09 UTC, marcinolokk commented on services/slowmode-app/main.cpp
>          return 0;
I got rid of the entire 'manual broadcast' functionality

2023-11-08 14:13 UTC, eyeam3 approved these changes

2023-11-09 12:02 UTC, merged